### ISSUE TITLE
some issue with file whatever.txt

### ISSUE THREAD

**Issue by JoostImpink** [JoostImpink/letshavefun#1]
when I run that file it doesn't work etc

![image](https://user-images.githubusercontent.com/12211202/49296307-de2b2f80-f485-11e8-820f-d75d05fd45ee.png)

this image clearly shows my issue

**Comment by JoostImpink** [comment]
by the way, it is very serious stuff --- whatever helpful comments

**Comment by dianaweng** [comment]
Mark, please get this done by 5pm yesterday.
